// web/src/components/ClusterList.tsx
import React, { useEffect, useState } from 'react';
import { Table, Button, Modal, Form, Input, Checkbox, message, Space, Upload } from 'antd';
import { EyeOutlined, CopyOutlined, DownloadOutlined, UploadOutlined, InboxOutlined } from '@ant-design/icons';
import type { UploadProps } from 'antd';
import api from '../api/client';

interface Cluster {
  id: number;
  name: string;
  description: string;
}

interface User {
  id: number;
  username: string;
}

const ClusterList: React.FC<{ role: string }> = ({ role }) => {
  const [clusters, setClusters] = useState<Cluster[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  
  // Permissions Modal State
  const [isPermModalOpen, setIsPermModalOpen] = useState(false);
  const [selectedCluster, setSelectedCluster] = useState<Cluster | null>(null);
  const [users, setUsers] = useState<User[]>([]);
  const [checkedUsers, setCheckedUsers] = useState<number[]>([]);

  // Kubeconfig Modal State
  const [isKubeconfigModalOpen, setIsKubeconfigModalOpen] = useState(false);
  const [kubeconfigContent, setKubeconfigContent] = useState('');
  const [isImportModalOpen, setIsImportModalOpen] = useState(false);

  const [form] = Form.useForm();
  const [importForm] = Form.useForm();

  const fetchClusters = async () => {
    const res = await api.get('/clusters');
    setClusters(res.data);
  };

  useEffect(() => {
    fetchClusters();
  }, []);

  const handleCreate = async (values: any) => {
    try {
      await api.post('/clusters', values);
      message.success('Cluster created');
      setIsModalOpen(false);
      form.resetFields();
      fetchClusters();
    } catch (err) {
      message.error('Failed to create cluster');
    }
  };

  const handleDelete = async (id: number) => {
    try {
      await api.delete(`/clusters/${id}`);
      message.success('Cluster deleted');
      fetchClusters();
    } catch (err) {
      message.error('Failed to delete cluster');
    }
  };

  const openPermModal = async (cluster: Cluster) => {
    setSelectedCluster(cluster);
    // Fetch all users
    const uRes = await api.get('/users');
    setUsers(uRes.data);
    
    // Fetch cluster permissions (which users have access)
    const pRes = await api.get(`/clusters/${cluster.id}/permissions`);
    setCheckedUsers(pRes.data.user_ids || []);
    
    setIsPermModalOpen(true);
  };

  const handleSavePerms = async () => {
    if (!selectedCluster) return;
    try {
      await api.post(`/clusters/${selectedCluster.id}/permissions`, { user_ids: checkedUsers });
      message.success('Permissions updated');
      setIsPermModalOpen(false);
    } catch (err) {
      message.error('Failed to update permissions');
    }
  };

  // Kubeconfig related functions
  const handleViewKubeconfig = async (cluster: Cluster) => {
    try {
      const res = await api.get(`/clusters/${cluster.id}/config`);
      setKubeconfigContent(res.data.kubeconfig);
      setSelectedCluster(cluster);
      setIsKubeconfigModalOpen(true);
    } catch (err) {
      message.error('Failed to fetch kubeconfig');
    }
  };

  const handleCopyKubeconfig = async (cluster: Cluster) => {
    try {
      const res = await api.get(`/clusters/${cluster.id}/config`);
      await navigator.clipboard.writeText(res.data.kubeconfig);
      message.success('Kubeconfig copied to clipboard');
    } catch (err) {
      message.error('Failed to copy kubeconfig');
    }
  };

  const handleExportKubeconfig = async (cluster: Cluster) => {
    try {
      const res = await api.get(`/clusters/${cluster.id}/config`);
      const blob = new Blob([res.data.kubeconfig], { type: 'text/yaml' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${cluster.name}-kubeconfig.yaml`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
      message.success('Kubeconfig exported');
    } catch (err) {
      message.error('Failed to export kubeconfig');
    }
  };

  const handleImportKubeconfig = (cluster: Cluster) => {
    setSelectedCluster(cluster);
    setIsImportModalOpen(true);
  };

  const handleImportSubmit = async (values: any) => {
    if (!selectedCluster) return;
    try {
      await api.post(`/clusters/${selectedCluster.id}/import`, { kubeconfig: values.kubeconfig });
      message.success('Kubeconfig imported successfully');
      setIsImportModalOpen(false);
      importForm.resetFields();
    } catch (err) {
      message.error('Failed to import kubeconfig');
    }
  };

  // File upload handlers
  const handleFileUpload: UploadProps['customRequest'] = ({ file, onSuccess, onError }) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      const content = e.target?.result as string;
      form.setFieldsValue({ kubeconfig: content });
      onSuccess?.(content);
      message.success('File uploaded successfully');
    };
    reader.onerror = () => {
      onError?.(new Error('Failed to read file'));
      message.error('Failed to read file');
    };
    reader.readAsText(file as File);
  };

  const uploadProps: UploadProps = {
    name: 'kubeconfig',
    multiple: false,
    accept: '.yaml,.yml,.txt',
    customRequest: handleFileUpload,
    showUploadList: false,
    beforeUpload: (file) => {
      const isValidType = file.type === 'text/yaml' || file.type === 'text/plain' || 
                         file.name.endsWith('.yaml') || file.name.endsWith('.yml') || file.name.endsWith('.txt');
      if (!isValidType) {
        message.error('Please upload a valid kubeconfig file (.yaml, .yml, or .txt)');
        return false;
      }
      const isLt10M = file.size / 1024 / 1024 < 10;
      if (!isLt10M) {
        message.error('File must be smaller than 10MB');
        return false;
      }
      return true;
    },
  };

  const columns = [
    { title: 'ID', dataIndex: 'id', key: 'id' },
    { title: 'Name', dataIndex: 'name', key: 'name' },
    { title: 'Description', dataIndex: 'description', key: 'description' },
    {
      title: 'Kubeconfig Actions',
      key: 'kubeconfig',
      render: (_: any, record: Cluster) => (
        <Space>
          <Button 
            type="primary" 
            icon={<EyeOutlined />} 
            size="small"
            onClick={() => handleViewKubeconfig(record)}
          >
            View
          </Button>
          <Button 
            type="default" 
            icon={<CopyOutlined />} 
            size="small"
            style={{ backgroundColor: '#52c41a', borderColor: '#52c41a', color: 'white' }}
            onClick={() => handleCopyKubeconfig(record)}
          >
            Copy
          </Button>
          <Button 
            type="default" 
            icon={<DownloadOutlined />} 
            size="small"
            style={{ backgroundColor: '#1890ff', borderColor: '#1890ff', color: 'white' }}
            onClick={() => handleExportKubeconfig(record)}
          >
            Export
          </Button>
          {role === 'admin' && (
            <Button 
              type="default" 
              icon={<UploadOutlined />} 
              size="small"
              style={{ backgroundColor: '#fa8c16', borderColor: '#fa8c16', color: 'white' }}
              onClick={() => handleImportKubeconfig(record)}
            >
              Import
            </Button>
          )}
        </Space>
      ),
    },
  ];

  if (role === 'admin') {
    columns.push({
      title: 'Admin Actions',
      key: 'admin_action',
      render: (_: any, record: Cluster) => (
        <Space>
          <Button onClick={() => openPermModal(record)}>Permissions</Button>
          <Button danger onClick={() => handleDelete(record.id)}>Delete</Button>
        </Space>
      ),
    } as any);
  }

  return (
    <div>
      <div style={{ marginBottom: 16 }}>
        {role === 'admin' && (
          <Button type="primary" onClick={() => setIsModalOpen(true)}>
            Add Cluster
          </Button>
        )}
      </div>
      <Table dataSource={clusters} columns={columns} rowKey="id" />

      <Modal title="Add Cluster" open={isModalOpen} onCancel={() => setIsModalOpen(false)} onOk={() => form.submit()}>
        <Form form={form} onFinish={handleCreate} layout="vertical">
          <Form.Item name="name" label="Name" rules={[{ required: true }]}>
            <Input />
          </Form.Item>
          <Form.Item name="description" label="Description">
            <Input />
          </Form.Item>
          <Form.Item name="kubeconfig" label="Kubeconfig (YAML Content)" rules={[{ required: true }]}>
            <Input.TextArea 
              rows={6} 
              placeholder="Paste kubeconfig content here or upload a file below..."
            />
          </Form.Item>
          <Form.Item label="Or Upload Kubeconfig File">
            <Upload.Dragger {...uploadProps}>
              <p className="ant-upload-drag-icon">
                <InboxOutlined />
              </p>
              <p className="ant-upload-text">Click or drag kubeconfig file to this area to upload</p>
              <p className="ant-upload-hint">
                Support for .yaml, .yml, or .txt files. File size should be less than 10MB.
              </p>
            </Upload.Dragger>
          </Form.Item>
        </Form>
      </Modal>

      <Modal 
        title={`Permissions for Cluster: ${selectedCluster?.name}`} 
        open={isPermModalOpen} 
        onCancel={() => setIsPermModalOpen(false)} 
        onOk={handleSavePerms}
      >
        <div style={{ marginBottom: 8 }}>Select users who can access this cluster:</div>
        <Checkbox.Group 
          style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}
          value={checkedUsers} 
          onChange={(vals) => setCheckedUsers(vals as number[])}
        >
          {users.map(u => (
            <Checkbox key={u.id} value={u.id}>{u.username}</Checkbox>
          ))}
        </Checkbox.Group>
      </Modal>

      {/* Kubeconfig View Modal */}
      <Modal 
        title={`Kubeconfig for Cluster: ${selectedCluster?.name}`} 
        open={isKubeconfigModalOpen} 
        onCancel={() => setIsKubeconfigModalOpen(false)}
        footer={[
          <Button key="close" onClick={() => setIsKubeconfigModalOpen(false)}>
            Close
          </Button>,
          <Button 
            key="copy" 
            type="primary" 
            onClick={() => {
              navigator.clipboard.writeText(kubeconfigContent);
              message.success('Kubeconfig copied to clipboard');
            }}
          >
            Copy to Clipboard
          </Button>,
        ]}
        width={800}
      >
        <Input.TextArea 
          value={kubeconfigContent} 
          rows={20} 
          readOnly 
          style={{ fontFamily: 'monospace', fontSize: '12px' }}
        />
      </Modal>

      {/* Import Kubeconfig Modal */}
      <Modal 
        title={`Import Kubeconfig for Cluster: ${selectedCluster?.name}`} 
        open={isImportModalOpen} 
        onCancel={() => setIsImportModalOpen(false)} 
        onOk={() => importForm.submit()}
      >
        <Form form={importForm} onFinish={handleImportSubmit} layout="vertical">
          <Form.Item 
            name="kubeconfig" 
            label="Kubeconfig Content" 
            rules={[{ required: true, message: 'Please input kubeconfig content' }]}
          >
            <Input.TextArea 
              rows={15} 
              placeholder="Paste your kubeconfig YAML content here..."
              style={{ fontFamily: 'monospace', fontSize: '12px' }}
            />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default ClusterList;

// web/src/views/clusters/ClusterList.vue
<template>
  <div>
    <div style="margin-bottom: 16px">
      <a-button v-if="canManageClusters" type="primary" @click="showCreateModal">
        添加集群
      </a-button>
    </div>

    <a-table
      :dataSource="clusters"
      :columns="columns"
      :loading="loading"
      row-key="id"
    >
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'kubeconfig'">
          <a-space>
            <a-button type="primary" size="small" @click="handleViewKubeconfig(record)">
              <template #icon><EyeOutlined /></template>
              查看
            </a-button>
            <a-button size="small" style="background: #52c41a; border-color: #52c41a; color: white" @click="handleCopyKubeconfig(record)">
              <template #icon><CopyOutlined /></template>
              复制
            </a-button>
            <a-button size="small" style="background: #1890ff; border-color: #1890ff; color: white" @click="handleExportKubeconfig(record)">
              <template #icon><DownloadOutlined /></template>
              导出
            </a-button>
            <a-button v-if="canManageClusters" size="small" style="background: #fa8c16; border-color: #fa8c16; color: white" @click="handleImportKubeconfig(record)">
              <template #icon><UploadOutlined /></template>
              导入
            </a-button>
          </a-space>
        </template>

        <template v-if="column.key === 'admin_action'">
          <a-space>
            <a-button size="small" @click="handlePermissions(record)">权限管理</a-button>
            <a-popconfirm
              title="确定要删除这个集群吗？"
              ok-text="确定"
              cancel-text="取消"
              @confirm="handleDelete(record.id)"
            >
              <a-button size="small" danger>删除</a-button>
            </a-popconfirm>
          </a-space>
        </template>
      </template>
    </a-table>

    <!-- 创建集群模态框 -->
    <a-modal
      v-model:open="createModalVisible"
      title="添加集群"
      @ok="handleCreateSubmit"
      :confirm-loading="submitting"
      width="600px"
    >
      <a-form :model="createForm" layout="vertical">
        <a-form-item label="集群名称" required>
          <a-input v-model:value="createForm.name" placeholder="请输入集群名称" />
        </a-form-item>
        <a-form-item label="描述">
          <a-input v-model:value="createForm.description" placeholder="请输入描述" />
        </a-form-item>
        <a-form-item label="Kubeconfig 内容" required>
          <a-textarea
            v-model:value="createForm.kubeconfig"
            :rows="8"
            placeholder="粘贴 kubeconfig 内容或使用下方上传文件"
          />
        </a-form-item>
        <a-form-item label="或上传 Kubeconfig 文件">
          <a-upload-dragger
            :before-upload="handleFileUpload"
            :show-upload-list="false"
            accept=".yaml,.yml,.txt"
          >
            <p class="ant-upload-drag-icon">
              <InboxOutlined />
            </p>
            <p class="ant-upload-text">点击或拖拽文件到此区域上传</p>
            <p class="ant-upload-hint">支持 .yaml, .yml, .txt 格式，文件大小不超过 10MB</p>
          </a-upload-dragger>
        </a-form-item>
      </a-form>
    </a-modal>

    <!-- 查看 Kubeconfig 模态框 -->
    <a-modal
      v-model:open="kubeconfigModalVisible"
      :title="`Kubeconfig - ${selectedCluster?.name}`"
      width="800px"
      @ok="kubeconfigModalVisible = false"
    >
      <template #footer>
        <a-button @click="kubeconfigModalVisible = false">关闭</a-button>
        <a-button type="primary" @click="handleCopyFromModal">复制到剪贴板</a-button>
      </template>
      <a-textarea
        :value="kubeconfigContent"
        :rows="20"
        readonly
        style="font-family: monospace; font-size: 12px"
      />
    </a-modal>

    <!-- 导入 Kubeconfig 模态框 -->
    <a-modal
      v-model:open="importModalVisible"
      :title="`导入 Kubeconfig - ${selectedCluster?.name}`"
      @ok="handleImportSubmit"
      :confirm-loading="submitting"
      width="600px"
    >
      <a-form :model="importForm" layout="vertical">
        <a-form-item label="Kubeconfig 内容" required>
          <a-textarea
            v-model:value="importForm.kubeconfig"
            :rows="15"
            placeholder="粘贴 kubeconfig YAML 内容..."
            style="font-family: monospace; font-size: 12px"
          />
        </a-form-item>
      </a-form>
    </a-modal>

    <!-- 权限管理模态框 -->
    <a-modal
      v-model:open="permissionsModalVisible"
      :title="`权限管理 - ${selectedCluster?.name}`"
      @ok="handlePermissionsSubmit"
      :confirm-loading="submitting"
    >
      <div style="margin-bottom: 8px">选择可以访问此集群的用户：</div>
      <a-checkbox-group v-model:value="selectedUserIds" style="display: flex; flex-direction: column; gap: 8px">
        <a-checkbox v-for="user in users" :key="user.id" :value="user.id">
          {{ user.username }}
        </a-checkbox>
      </a-checkbox-group>
    </a-modal>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { message } from 'ant-design-vue'
import {
  EyeOutlined,
  CopyOutlined,
  DownloadOutlined,
  UploadOutlined,
  InboxOutlined
} from '@ant-design/icons-vue'
import { useClusterStore, useUserStore } from '@/stores'
import { usePermission } from '@/composables'
import type { Cluster, CreateClusterDto } from '@/types'
import type { UploadProps } from 'ant-design-vue'

const clusterStore = useClusterStore()
const userStore = useUserStore()
const { canManageClusters } = usePermission()

const loading = ref(false)
const submitting = ref(false)
const createModalVisible = ref(false)
const kubeconfigModalVisible = ref(false)
const importModalVisible = ref(false)
const permissionsModalVisible = ref(false)

const selectedCluster = ref<Cluster | null>(null)
const kubeconfigContent = ref('')
const selectedUserIds = ref<number[]>([])

const createForm = ref<CreateClusterDto>({
  name: '',
  description: '',
  kubeconfig: ''
})

const importForm = ref({
  kubeconfig: ''
})

const clusters = computed(() => clusterStore.clusters)
const users = computed(() => userStore.users)

const columns = computed(() => {
  const baseColumns = [
    { title: 'ID', dataIndex: 'id', key: 'id' },
    { title: '名称', dataIndex: 'name', key: 'name' },
    { title: '描述', dataIndex: 'description', key: 'description' },
    { title: 'Kubeconfig 操作', key: 'kubeconfig' }
  ]

  if (canManageClusters.value) {
    baseColumns.push({ title: '管理操作', key: 'admin_action' })
  }

  return baseColumns
})

onMounted(async () => {
  await fetchData()
})

const fetchData = async () => {
  loading.value = true
  try {
    await clusterStore.fetchClusters()
    if (canManageClusters.value) {
      await userStore.fetchUsers()
    }
  } catch (error) {
    console.error('Failed to fetch data:', error)
  } finally {
    loading.value = false
  }
}

const showCreateModal = () => {
  createForm.value = {
    name: '',
    description: '',
    kubeconfig: ''
  }
  createModalVisible.value = true
}

const handleCreateSubmit = async () => {
  if (!createForm.value.name || !createForm.value.kubeconfig) {
    message.error('请填写必填字段')
    return
  }

  submitting.value = true
  try {
    await clusterStore.createCluster(createForm.value)
    message.success('集群创建成功')
    createModalVisible.value = false
    await clusterStore.fetchClusters()
  } catch (error) {
    console.error('Failed to create cluster:', error)
  } finally {
    submitting.value = false
  }
}

const handleDelete = async (id: number) => {
  try {
    await clusterStore.deleteCluster(id)
    message.success('集群删除成功')
  } catch (error) {
    console.error('Failed to delete cluster:', error)
  }
}

const handleViewKubeconfig = async (cluster: Cluster) => {
  try {
    kubeconfigContent.value = await clusterStore.getKubeconfig(cluster.id)
    selectedCluster.value = cluster
    kubeconfigModalVisible.value = true
  } catch (error) {
    console.error('Failed to fetch kubeconfig:', error)
  }
}

const handleCopyKubeconfig = async (cluster: Cluster) => {
  try {
    const config = await clusterStore.getKubeconfig(cluster.id)
    await navigator.clipboard.writeText(config)
    message.success('Kubeconfig 已复制到剪贴板')
  } catch (error) {
    console.error('Failed to copy kubeconfig:', error)
    message.error('复制失败')
  }
}

const handleCopyFromModal = async () => {
  try {
    await navigator.clipboard.writeText(kubeconfigContent.value)
    message.success('Kubeconfig 已复制到剪贴板')
  } catch (error) {
    message.error('复制失败')
  }
}

const handleExportKubeconfig = async (cluster: Cluster) => {
  try {
    const config = await clusterStore.getKubeconfig(cluster.id)
    const blob = new Blob([config], { type: 'text/yaml' })
    const url = window.URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${cluster.name}-kubeconfig.yaml`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    window.URL.revokeObjectURL(url)
    message.success('Kubeconfig 导出成功')
  } catch (error) {
    console.error('Failed to export kubeconfig:', error)
  }
}

const handleImportKubeconfig = (cluster: Cluster) => {
  selectedCluster.value = cluster
  importForm.value.kubeconfig = ''
  importModalVisible.value = true
}

const handleImportSubmit = async () => {
  if (!selectedCluster.value || !importForm.value.kubeconfig) {
    message.error('请输入 Kubeconfig 内容')
    return
  }

  submitting.value = true
  try {
    await clusterStore.importKubeconfig(selectedCluster.value.id, {
      kubeconfig: importForm.value.kubeconfig
    })
    message.success('Kubeconfig 导入成功')
    importModalVisible.value = false
  } catch (error) {
    console.error('Failed to import kubeconfig:', error)
  } finally {
    submitting.value = false
  }
}

const handleFileUpload: UploadProps['beforeUpload'] = (file) => {
  const isValidType = file.type === 'text/yaml' || file.type === 'text/plain' ||
    file.name.endsWith('.yaml') || file.name.endsWith('.yml') || file.name.endsWith('.txt')
  
  if (!isValidType) {
    message.error('请上传有效的 kubeconfig 文件 (.yaml, .yml, 或 .txt)')
    return false
  }

  const isLt10M = file.size / 1024 / 1024 < 10
  if (!isLt10M) {
    message.error('文件大小不能超过 10MB')
    return false
  }

  const reader = new FileReader()
  reader.onload = (e) => {
    const content = e.target?.result as string
    createForm.value.kubeconfig = content
    message.success('文件上传成功')
  }
  reader.onerror = () => {
    message.error('文件读取失败')
  }
  reader.readAsText(file)

  return false
}

const handlePermissions = async (cluster: Cluster) => {
  selectedCluster.value = cluster
  try {
    selectedUserIds.value = await clusterStore.fetchClusterPermissions(cluster.id)
    permissionsModalVisible.value = true
  } catch (error) {
    console.error('Failed to fetch permissions:', error)
  }
}

const handlePermissionsSubmit = async () => {
  if (!selectedCluster.value) return

  submitting.value = true
  try {
    await clusterStore.updateClusterPermissions(selectedCluster.value.id, selectedUserIds.value)
    message.success('权限更新成功')
    permissionsModalVisible.value = false
  } catch (error) {
    console.error('Failed to update permissions:', error)
  } finally {
    submitting.value = false
  }
}
</script>
