// web/src/views/users/UserList.vue
<template>
  <div>
    <div style="margin-bottom: 16px">
      <a-button type="primary" @click="showCreateModal">
        创建用户
      </a-button>
    </div>

    <a-table
      :dataSource="users"
      :columns="columns"
      :loading="loading"
      row-key="id"
    >
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'actions'">
          <a-space>
            <a-button size="small" @click="handlePermissions(record)">
              <template #icon><UserOutlined /></template>
              权限
            </a-button>

            <a-button
              v-if="isCurrentUser(record)"
              size="small"
              type="primary"
              @click="showPasswordModal"
            >
              <template #icon><KeyOutlined /></template>
              修改密码
            </a-button>

            <template v-if="isAdmin && !isCurrentUser(record)">
              <a-button
                size="small"
                style="background: #fa8c16; border-color: #fa8c16; color: white"
                @click="handleResetPassword(record)"
              >
                <template #icon><KeyOutlined /></template>
                重置密码
              </a-button>

              <a-button
                size="small"
                style="background: #722ed1; border-color: #722ed1; color: white"
                @click="handleChangeRole(record)"
              >
                <template #icon><EditOutlined /></template>
                修改角色
              </a-button>

              <a-popconfirm
                v-if="record.role !== 'admin'"
                title="确定要删除这个用户吗？"
                ok-text="确定"
                cancel-text="取消"
                @confirm="handleDelete(record.id)"
              >
                <a-button size="small" danger>
                  <template #icon><DeleteOutlined /></template>
                  删除
                </a-button>
              </a-popconfirm>
            </template>
          </a-space>
        </template>
      </template>
    </a-table>

    <!-- 创建用户模态框 -->
    <a-modal
      v-model:open="createModalVisible"
      title="创建用户"
      @ok="handleCreateSubmit"
      :confirm-loading="submitting"
    >
      <a-form :model="createForm" layout="vertical">
        <a-form-item label="用户名" required>
          <a-input v-model:value="createForm.username" placeholder="请输入用户名" />
        </a-form-item>
        <a-form-item label="密码" required>
          <a-input-password v-model:value="createForm.password" placeholder="请输入密码" />
        </a-form-item>
        <a-form-item label="角色" required>
          <a-select v-model:value="createForm.role" placeholder="请选择角色">
            <a-select-option value="user">普通用户</a-select-option>
            <a-select-option value="admin">管理员</a-select-option>
          </a-select>
        </a-form-item>
      </a-form>
    </a-modal>

    <!-- 修改密码模态框（当前用户） -->
    <a-modal
      v-model:open="passwordModalVisible"
      title="修改密码"
      @ok="handlePasswordSubmit"
      :confirm-loading="submitting"
    >
      <a-form :model="passwordForm" layout="vertical">
        <a-form-item label="当前密码" required>
          <a-input-password v-model:value="passwordForm.old_password" placeholder="请输入当前密码" />
        </a-form-item>
        <a-form-item label="新密码" required>
          <a-input-password v-model:value="passwordForm.new_password" placeholder="请输入新密码（至少6个字符）" />
        </a-form-item>
        <a-form-item label="确认新密码" required>
          <a-input-password v-model:value="passwordForm.confirm_password" placeholder="请再次输入新密码" />
        </a-form-item>
      </a-form>
    </a-modal>

    <!-- 重置密码模态框（管理员） -->
    <a-modal
      v-model:open="resetPasswordModalVisible"
      :title="`重置密码 - ${selectedUser?.username}`"
      @ok="handleResetPasswordSubmit"
      :confirm-loading="submitting"
    >
      <a-form :model="resetPasswordForm" layout="vertical">
        <a-form-item label="新密码" required>
          <a-input-password v-model:value="resetPasswordForm.new_password" placeholder="请输入新密码（至少6个字符）" />
        </a-form-item>
        <a-form-item label="确认新密码" required>
          <a-input-password v-model:value="resetPasswordForm.confirm_password" placeholder="请再次输入新密码" />
        </a-form-item>
      </a-form>
    </a-modal>

    <!-- 修改角色模态框 -->
    <a-modal
      v-model:open="roleModalVisible"
      :title="`修改角色 - ${selectedUser?.username}`"
      @ok="handleRoleSubmit"
      :confirm-loading="submitting"
    >
      <a-form :model="roleForm" layout="vertical">
        <a-form-item label="角色" required>
          <a-select v-model:value="roleForm.role" placeholder="请选择角色">
            <a-select-option value="user">普通用户</a-select-option>
            <a-select-option value="admin">管理员</a-select-option>
          </a-select>
        </a-form-item>
      </a-form>
    </a-modal>

    <!-- 权限管理模态框 -->
    <a-modal
      v-model:open="permissionsModalVisible"
      :title="`权限管理 - ${selectedUser?.username}`"
      @ok="handlePermissionsSubmit"
      :confirm-loading="submitting"
    >
      <div style="margin-bottom: 8px">选择用户可以访问的集群：</div>
      <a-checkbox-group v-model:value="selectedClusterIds" style="display: flex; flex-direction: column; gap: 8px">
        <a-checkbox v-for="cluster in clusters" :key="cluster.id" :value="cluster.id">
          {{ cluster.name }}
        </a-checkbox>
      </a-checkbox-group>
    </a-modal>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { message } from 'ant-design-vue'
import {
  UserOutlined,
  KeyOutlined,
  EditOutlined,
  DeleteOutlined
} from '@ant-design/icons-vue'
import { useUserStore, useClusterStore, useAuthStore } from '@/stores'
import type { User, CreateUserDto, UserRole } from '@/types'

const userStore = useUserStore()
const clusterStore = useClusterStore()
const authStore = useAuthStore()

const loading = ref(false)
const submitting = ref(false)
const createModalVisible = ref(false)
const passwordModalVisible = ref(false)
const resetPasswordModalVisible = ref(false)
const roleModalVisible = ref(false)
const permissionsModalVisible = ref(false)

const selectedUser = ref<User | null>(null)
const selectedClusterIds = ref<number[]>([])

const createForm = ref<CreateUserDto>({
  username: '',
  password: '',
  role: 'user' as UserRole
})

const passwordForm = ref({
  old_password: '',
  new_password: '',
  confirm_password: ''
})

const resetPasswordForm = ref({
  new_password: '',
  confirm_password: ''
})

const roleForm = ref({
  role: 'user' as UserRole
})

const users = computed(() => userStore.users)
const clusters = computed(() => clusterStore.clusters)
const isAdmin = computed(() => authStore.isAdmin)
const currentUser = computed(() => authStore.currentUser)

const columns = [
  { title: 'ID', dataIndex: 'id', key: 'id' },
  { title: '用户名', dataIndex: 'username', key: 'username' },
  { title: '角色', dataIndex: 'role', key: 'role' },
  { title: '操作', key: 'actions' }
]

const isCurrentUser = (user: User) => {
  return currentUser.value?.username === user.username
}

onMounted(async () => {
  await fetchData()
})

const fetchData = async () => {
  loading.value = true
  try {
    await userStore.fetchUsers()
    await clusterStore.fetchClusters()
  } catch (error) {
    console.error('Failed to fetch data:', error)
  } finally {
    loading.value = false
  }
}

const showCreateModal = () => {
  createForm.value = {
    username: '',
    password: '',
    role: 'user'
  }
  createModalVisible.value = true
}

const handleCreateSubmit = async () => {
  if (!createForm.value.username || !createForm.value.password) {
    message.error('请填写必填字段')
    return
  }

  if (createForm.value.password.length < 6) {
    message.error('密码至少需要6个字符')
    return
  }

  submitting.value = true
  try {
    await userStore.createUser(createForm.value)
    message.success('用户创建成功')
    createModalVisible.value = false
  } catch (error) {
    console.error('Failed to create user:', error)
  } finally {
    submitting.value = false
  }
}

const handleDelete = async (id: number) => {
  try {
    await userStore.deleteUser(id)
    message.success('用户删除成功')
  } catch (error) {
    console.error('Failed to delete user:', error)
  }
}

const showPasswordModal = () => {
  passwordForm.value = {
    old_password: '',
    new_password: '',
    confirm_password: ''
  }
  passwordModalVisible.value = true
}

const handlePasswordSubmit = async () => {
  if (!passwordForm.value.old_password || !passwordForm.value.new_password) {
    message.error('请填写所有字段')
    return
  }

  if (passwordForm.value.new_password.length < 6) {
    message.error('新密码至少需要6个字符')
    return
  }

  if (passwordForm.value.new_password !== passwordForm.value.confirm_password) {
    message.error('两次输入的密码不一致')
    return
  }

  submitting.value = true
  try {
    await authStore.updatePassword(passwordForm.value.old_password, passwordForm.value.new_password)
    message.success('密码修改成功')
    passwordModalVisible.value = false
  } catch (error) {
    console.error('Failed to update password:', error)
  } finally {
    submitting.value = false
  }
}

const handleResetPassword = (user: User) => {
  selectedUser.value = user
  resetPasswordForm.value = {
    new_password: '',
    confirm_password: ''
  }
  resetPasswordModalVisible.value = true
}

const handleResetPasswordSubmit = async () => {
  if (!selectedUser.value || !resetPasswordForm.value.new_password) {
    message.error('请填写所有字段')
    return
  }

  if (resetPasswordForm.value.new_password.length < 6) {
    message.error('新密码至少需要6个字符')
    return
  }

  if (resetPasswordForm.value.new_password !== resetPasswordForm.value.confirm_password) {
    message.error('两次输入的密码不一致')
    return
  }

  submitting.value = true
  try {
    await userStore.resetPassword(selectedUser.value.id, resetPasswordForm.value.new_password)
    message.success('密码重置成功')
    resetPasswordModalVisible.value = false
  } catch (error) {
    console.error('Failed to reset password:', error)
  } finally {
    submitting.value = false
  }
}

const handleChangeRole = (user: User) => {
  selectedUser.value = user
  roleForm.value.role = user.role
  roleModalVisible.value = true
}

const handleRoleSubmit = async () => {
  if (!selectedUser.value) return

  submitting.value = true
  try {
    await userStore.updateUserRole(selectedUser.value.id, roleForm.value.role)
    message.success('角色修改成功')
    roleModalVisible.value = false
  } catch (error) {
    console.error('Failed to update role:', error)
  } finally {
    submitting.value = false
  }
}

const handlePermissions = async (user: User) => {
  selectedUser.value = user
  try {
    selectedClusterIds.value = await userStore.fetchUserPermissions(user.id)
    permissionsModalVisible.value = true
  } catch (error) {
    console.error('Failed to fetch permissions:', error)
  }
}

const handlePermissionsSubmit = async () => {
  if (!selectedUser.value) return

  submitting.value = true
  try {
    await userStore.updateUserPermissions(selectedUser.value.id, selectedClusterIds.value)
    message.success('权限更新成功')
    permissionsModalVisible.value = false
  } catch (error) {
    console.error('Failed to update permissions:', error)
  } finally {
    submitting.value = false
  }
}
</script>

// web/src/components/UserList.tsx
import React, { useEffect, useState } from 'react';
import { Table, Button, Modal, Form, Input, Select, Checkbox, message, Space, Popconfirm } from 'antd';
import { EditOutlined, DeleteOutlined, KeyOutlined, UserOutlined } from '@ant-design/icons';
import api from '../api/client';

interface User {
  id: number;
  username: string;
  role: string;
}

interface Cluster {
  id: number;
  name: string;
}

const UserList: React.FC = () => {
  const [users, setUsers] = useState<User[]>([]);
  const [currentUser, setCurrentUser] = useState<{ username: string; role: string } | null>(null);
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [isPermModalOpen, setIsPermModalOpen] = useState(false);
  const [isPasswordModalOpen, setIsPasswordModalOpen] = useState(false);
  const [isAdminPasswordModalOpen, setIsAdminPasswordModalOpen] = useState(false);
  const [isRoleModalOpen, setIsRoleModalOpen] = useState(false);
  const [selectedUser, setSelectedUser] = useState<User | null>(null);
  const [clusters, setClusters] = useState<Cluster[]>([]);
  const [checkedClusters, setCheckedClusters] = useState<number[]>([]);
  
  const [form] = Form.useForm();
  const [passwordForm] = Form.useForm();
  const [adminPasswordForm] = Form.useForm();
  const [roleForm] = Form.useForm();

  const fetchUsers = async () => {
    const res = await api.get('/users');
    setUsers(res.data);
  };

  const fetchCurrentUser = async () => {
    try {
      const res = await api.get('/my/user');
      setCurrentUser(res.data);
    } catch (err) {
      message.error('Failed to fetch current user info');
    }
  };

  useEffect(() => {
    fetchUsers();
    fetchCurrentUser();
  }, []);

  const handleCreate = async (values: any) => {
    try {
      await api.post('/users', values);
      message.success('User created');
      setIsCreateModalOpen(false);
      form.resetFields();
      fetchUsers();
    } catch (err) {
      message.error('Failed to create user');
    }
  };

  const openPermModal = async (user: User) => {
    setSelectedUser(user);
    // Fetch all clusters
    const cRes = await api.get('/clusters'); // Admin gets all
    setClusters(cRes.data);
    
    // Fetch user permissions
    const pRes = await api.get(`/users/${user.id}/permissions`);
    setCheckedClusters(pRes.data.cluster_ids || []);
    
    setIsPermModalOpen(true);
  };

  const handleSavePerms = async () => {
    if (!selectedUser) return;
    try {
      await api.post(`/users/${selectedUser.id}/permissions`, { cluster_ids: checkedClusters });
      message.success('Permissions updated');
      setIsPermModalOpen(false);
    } catch (err) {
      message.error('Failed to update permissions');
    }
  };

  // Password change handlers
  const handleChangePassword = async (values: any) => {
    try {
      await api.post('/my/password', values);
      message.success('Password changed successfully');
      setIsPasswordModalOpen(false);
      passwordForm.resetFields();
    } catch (err) {
      message.error('Failed to change password');
    }
  };

  const handleAdminChangePassword = async (values: any) => {
    if (!selectedUser) return;
    try {
      await api.post(`/users/${selectedUser.id}/password`, { new_password: values.new_password });
      message.success('Password changed successfully');
      setIsAdminPasswordModalOpen(false);
      adminPasswordForm.resetFields();
    } catch (err) {
      message.error('Failed to change password');
    }
  };

  const handleDeleteUser = async (user: User) => {
    try {
      await api.delete(`/users/${user.id}`);
      message.success('User deleted successfully');
      fetchUsers();
    } catch (err) {
      message.error('Failed to delete user');
    }
  };

  const handleUpdateRole = async (values: any) => {
    if (!selectedUser) return;
    try {
      await api.post(`/users/${selectedUser.id}/role`, values);
      message.success('User role updated successfully');
      setIsRoleModalOpen(false);
      roleForm.resetFields();
      fetchUsers();
    } catch (err) {
      message.error('Failed to update user role');
    }
  };

  // Modal handlers
  const openPasswordModal = () => {
    setIsPasswordModalOpen(true);
  };

  const openAdminPasswordModal = (user: User) => {
    setSelectedUser(user);
    setIsAdminPasswordModalOpen(true);
  };

  const openRoleModal = (user: User) => {
    setSelectedUser(user);
    roleForm.setFieldsValue({ role: user.role });
    setIsRoleModalOpen(true);
  };

  const columns = [
    { title: 'ID', dataIndex: 'id', key: 'id' },
    { title: 'Username', dataIndex: 'username', key: 'username' },
    { title: 'Role', dataIndex: 'role', key: 'role' },
    {
      title: 'Actions',
      key: 'action',
      render: (_: any, record: User) => {
        const isCurrentUser = currentUser?.username === record.username;
        const isAdmin = currentUser?.role === 'admin';
        
        return (
          <Space>
            <Button 
              size="small" 
              onClick={() => openPermModal(record)}
              icon={<UserOutlined />}
            >
              Permissions
            </Button>
            
            {isCurrentUser && (
              <Button 
                size="small" 
                type="primary"
                onClick={openPasswordModal}
                icon={<KeyOutlined />}
              >
                Change Password
              </Button>
            )}
            
            {isAdmin && !isCurrentUser && (
              <>
                <Button 
                  size="small" 
                  onClick={() => openAdminPasswordModal(record)}
                  icon={<KeyOutlined />}
                  style={{ backgroundColor: '#fa8c16', borderColor: '#fa8c16', color: 'white' }}
                >
                  Reset Password
                </Button>
                
                <Button 
                  size="small" 
                  onClick={() => openRoleModal(record)}
                  icon={<EditOutlined />}
                  style={{ backgroundColor: '#722ed1', borderColor: '#722ed1', color: 'white' }}
                >
                  Change Role
                </Button>
                
                {record.role !== 'admin' && (
                  <Popconfirm
                    title="Delete User"
                    description="Are you sure you want to delete this user?"
                    onConfirm={() => handleDeleteUser(record)}
                    okText="Yes"
                    cancelText="No"
                  >
                    <Button 
                      size="small" 
                      danger
                      icon={<DeleteOutlined />}
                    >
                      Delete
                    </Button>
                  </Popconfirm>
                )}
              </>
            )}
          </Space>
        );
      },
    },
  ];

  return (
    <div>
      <div style={{ marginBottom: 16 }}>
        <Button type="primary" onClick={() => setIsCreateModalOpen(true)}>Create User</Button>
      </div>
      <Table dataSource={users} columns={columns} rowKey="id" />

      <Modal title="Create User" open={isCreateModalOpen} onCancel={() => setIsCreateModalOpen(false)} onOk={() => form.submit()}>
        <Form form={form} onFinish={handleCreate} layout="vertical">
          <Form.Item name="username" label="Username" rules={[{ required: true }]}>
            <Input />
          </Form.Item>
          <Form.Item name="password" label="Password" rules={[{ required: true }]}>
            <Input.Password />
          </Form.Item>
          <Form.Item name="role" label="Role" rules={[{ required: true }]}>
            <Select>
              <Select.Option value="user">User</Select.Option>
              <Select.Option value="admin">Admin</Select.Option>
            </Select>
          </Form.Item>
        </Form>
      </Modal>

      <Modal title={`Permissions for ${selectedUser?.username}`} open={isPermModalOpen} onCancel={() => setIsPermModalOpen(false)} onOk={handleSavePerms}>
        <Checkbox.Group 
          style={{ display: 'flex', flexDirection: 'column' }}
          value={checkedClusters} 
          onChange={(vals) => setCheckedClusters(vals as number[])}
        >
          {clusters.map(c => (
            <Checkbox key={c.id} value={c.id}>{c.name}</Checkbox>
          ))}
        </Checkbox.Group>
      </Modal>

      {/* Change Password Modal (for current user) */}
      <Modal 
        title="Change Password" 
        open={isPasswordModalOpen} 
        onCancel={() => setIsPasswordModalOpen(false)} 
        onOk={() => passwordForm.submit()}
      >
        <Form form={passwordForm} onFinish={handleChangePassword} layout="vertical">
          <Form.Item 
            name="old_password" 
            label="Current Password" 
            rules={[{ required: true, message: 'Please input your current password' }]}
          >
            <Input.Password />
          </Form.Item>
          <Form.Item 
            name="new_password" 
            label="New Password" 
            rules={[
              { required: true, message: 'Please input your new password' },
              { min: 6, message: 'Password must be at least 6 characters' }
            ]}
          >
            <Input.Password />
          </Form.Item>
          <Form.Item 
            name="confirm_password" 
            label="Confirm New Password"
            dependencies={['new_password']}
            rules={[
              { required: true, message: 'Please confirm your new password' },
              ({ getFieldValue }) => ({
                validator(_, value) {
                  if (!value || getFieldValue('new_password') === value) {
                    return Promise.resolve();
                  }
                  return Promise.reject(new Error('Passwords do not match'));
                },
              }),
            ]}
          >
            <Input.Password />
          </Form.Item>
        </Form>
      </Modal>

      {/* Admin Change Password Modal */}
      <Modal 
        title={`Reset Password for ${selectedUser?.username}`} 
        open={isAdminPasswordModalOpen} 
        onCancel={() => setIsAdminPasswordModalOpen(false)} 
        onOk={() => adminPasswordForm.submit()}
      >
        <Form form={adminPasswordForm} onFinish={handleAdminChangePassword} layout="vertical">
          <Form.Item 
            name="new_password" 
            label="New Password" 
            rules={[
              { required: true, message: 'Please input the new password' },
              { min: 6, message: 'Password must be at least 6 characters' }
            ]}
          >
            <Input.Password />
          </Form.Item>
          <Form.Item 
            name="confirm_password" 
            label="Confirm New Password"
            dependencies={['new_password']}
            rules={[
              { required: true, message: 'Please confirm the new password' },
              ({ getFieldValue }) => ({
                validator(_, value) {
                  if (!value || getFieldValue('new_password') === value) {
                    return Promise.resolve();
                  }
                  return Promise.reject(new Error('Passwords do not match'));
                },
              }),
            ]}
          >
            <Input.Password />
          </Form.Item>
        </Form>
      </Modal>

      {/* Change Role Modal */}
      <Modal 
        title={`Change Role for ${selectedUser?.username}`} 
        open={isRoleModalOpen} 
        onCancel={() => setIsRoleModalOpen(false)} 
        onOk={() => roleForm.submit()}
      >
        <Form form={roleForm} onFinish={handleUpdateRole} layout="vertical">
          <Form.Item 
            name="role" 
            label="Role" 
            rules={[{ required: true, message: 'Please select a role' }]}
          >
            <Select>
              <Select.Option value="user">User</Select.Option>
              <Select.Option value="admin">Admin</Select.Option>
            </Select>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default UserList;
